# -*- coding: utf-8 -*-
"""per_sensor_model_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LnjKrKev58fv-kuVlPImGnOmljWAgjV1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
import xgboost as xgb

# ========== LOAD YOUR DATA ==========
df = pd.read_excel("/Users/venkatchandan/Desktop/sensor_calibration_project/15.xlsx")

# ====== CONFIGURE COLUMNS ======
time_col = 'Time'
reference_col = 'Reference monitor'
sensor_cols = [col for col in df.columns if col not in [time_col, reference_col]]
y_full = df[reference_col]

# ====== OUTPUT WRITER ======
writer = pd.ExcelWriter("per_sensor_model_predictions.xlsx", engine="xlsxwriter")

# ====== METRIC FUNCTION ======
def compute_metrics(y_true, y_pred):
    return {
        'MAE': mean_absolute_error(y_true, y_pred),
        'MSE': mean_squared_error(y_true, y_pred),
        'R2': r2_score(y_true, y_pred)
    }

# ====== FOR EACH SENSOR COLUMN ======
for sensor in sensor_cols:
    print(f"🔍 Processing sensor: {sensor}")
    X = df[[sensor]]
    X_train, X_test, y_train, y_test = train_test_split(X, y_full, test_size=0.2, random_state=42)

    # ==== RANDOM FOREST ====
    rf_grid = {
        'n_estimators': [50, 100, 200],
        'max_depth': [3, 5, 10],
        'min_samples_split': [2, 5],
        'min_samples_leaf': [1, 2]
    }
    rf = RandomForestRegressor(random_state=42)
    rf_cv = GridSearchCV(rf, rf_grid, cv=5, scoring='r2', n_jobs=-1, verbose=1)
    rf_cv.fit(X_train, y_train)
    rf_best = rf_cv.best_estimator_

    rf_pred_all = rf_best.predict(X)
    rf_pred_test = rf_best.predict(X_test)

    rf_metrics_all = compute_metrics(y_full, rf_pred_all)
    rf_metrics_test = compute_metrics(y_test, rf_pred_test)

    pd.DataFrame({'Actual': y_full.reset_index(drop=True), 'Predicted': rf_pred_all}).to_excel(writer, sheet_name=f'RF_{sensor}', index=False)
    pd.DataFrame([rf_metrics_all]).to_excel(writer, sheet_name=f'RF_{sensor}_Metrics', index=False)
    pd.DataFrame({'Actual': y_test.reset_index(drop=True), 'Predicted': rf_pred_test}).to_excel(writer, sheet_name=f'RF_{sensor}_Test', index=False)
    pd.DataFrame([rf_metrics_test]).to_excel(writer, sheet_name=f'RF_{sensor}_TestMetrics', index=False)

    # ==== XGBOOST ====
    xgb_grid = {
        'n_estimators': [100, 200],
        'max_depth': [3, 5],
        'learning_rate': [0.1],
        'subsample': [1.0],
        'colsample_bytree': [1.0]
    }
    xgb_model = xgb.XGBRegressor(objective='reg:squarederror', random_state=42)
    xgb_cv = GridSearchCV(xgb_model, xgb_grid, cv=5, scoring='r2', n_jobs=-1)
    xgb_cv.fit(X_train, y_train)
    xgb_best = xgb_cv.best_estimator_

    xgb_pred_all = xgb_best.predict(X)
    xgb_pred_test = xgb_best.predict(X_test)

    xgb_metrics_all = compute_metrics(y_full, xgb_pred_all)
    xgb_metrics_test = compute_metrics(y_test, xgb_pred_test)

    pd.DataFrame({'Actual': y_full.reset_index(drop=True), 'Predicted': xgb_pred_all}).to_excel(writer, sheet_name=f'XGB_{sensor}', index=False)
    pd.DataFrame([xgb_metrics_all]).to_excel(writer, sheet_name=f'XGB_{sensor}_Metrics', index=False)
    pd.DataFrame({'Actual': y_test.reset_index(drop=True), 'Predicted': xgb_pred_test}).to_excel(writer, sheet_name=f'XGB_{sensor}_Test', index=False)
    pd.DataFrame([xgb_metrics_test]).to_excel(writer, sheet_name=f'XGB_{sensor}_TestMetrics', index=False)

    # ==== SVR ====
    svr_pipeline = make_pipeline(StandardScaler(), SVR())
    svr_grid = {
        'svr__C': [1, 10, 100],
        'svr__gamma': [0.01, 0.1],
        'svr__epsilon': [0.01, 0.1],
        'svr__kernel': ['rbf']
    }
    svr_cv = GridSearchCV(svr_pipeline, svr_grid, cv=5, scoring='r2', n_jobs=-1)
    svr_cv.fit(X_train, y_train)
    svr_best = svr_cv.best_estimator_

    svr_pred_all = svr_best.predict(X)
    svr_pred_test = svr_best.predict(X_test)

    svr_metrics_all = compute_metrics(y_full, svr_pred_all)
    svr_metrics_test = compute_metrics(y_test, svr_pred_test)

    pd.DataFrame({'Actual': y_full.reset_index(drop=True), 'Predicted': svr_pred_all}).to_excel(writer, sheet_name=f'SVR_{sensor}', index=False)
    pd.DataFrame([svr_metrics_all]).to_excel(writer, sheet_name=f'SVR_{sensor}_Metrics', index=False)
    pd.DataFrame({'Actual': y_test.reset_index(drop=True), 'Predicted': svr_pred_test}).to_excel(writer, sheet_name=f'SVR_{sensor}_Test', index=False)
    pd.DataFrame([svr_metrics_test]).to_excel(writer, sheet_name=f'SVR_{sensor}_TestMetrics', index=False)

    # LOGGING
    print(f"✅ {sensor} :: RF R²: {rf_metrics_test['R2']:.4f}, XGB R²: {xgb_metrics_test['R2']:.4f}, SVR R²: {svr_metrics_test['R2']:.4f}")

# ====== SAVE EXCEL FILE ======
writer.close()
print("✅ All models trained and results written to Excel.")